name: Publish for .NET 8.0

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - '*.yml'
      - '.gitignore'
      - 'LICENSE'
      - 'latest.json'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up .NET 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Set build number
      run: |
        sed -i 's/public static readonly string CurrentVersion = ".*";/public static readonly string CurrentVersion = "${{ github.run_number }}";/' '/home/runner/work/HTML2EXE-2.0/HTML2EXE-2.0/HTML2EXE 2.0/Program.cs'

    - name: Restore dependencies
      run: dotnet restore -p:EnableWindowsTargeting=true

    - name: Build and publish main app (self-contained)
      run: dotnet publish "HTML2EXE 2.0" -c Release -r win-x64 -p:PublishSingleFile=true --self-contained true -o ./publish-big -p:PublishReadyToRun=true -p:EnableWindowsTargeting=true -p:DefineConstants="BIG_BUILD"

    - name: Rename HTML2EXE-big.exe
      run: mv "./publish-big/HTML2EXE 2.0.exe" "./publish-big/HTML2EXE-big.exe"

    - name: Build and publish WebView (self-contained)
      run: dotnet publish HTML2EXE_Webview -c Release -r win-x64 -p:PublishSingleFile=true --self-contained true -o ./webview_publish_big -p:EnableWindowsTargeting=true

    - name: Rename webview-big.exe
      run: mv "./webview_publish_big/Webview.exe" "./webview_publish_big/webview-big.exe"

    - name: Upload HTML2EXE-big.exe artifact
      uses: actions/upload-artifact@v4
      with:
        name: HTML2EXE-big
        path: ./publish-big/HTML2EXE-big.exe

    - name: Upload webview-big.exe artifact
      uses: actions/upload-artifact@v4
      with:
        name: webview-big
        path: ./webview_publish_big/webview-big.exe

    - name: Build and publish main app
      run: dotnet publish "HTML2EXE 2.0" -c Release -r win-x64 -p:PublishSingleFile=true --self-contained false -o ./publish -p:PublishReadyToRun=true -p:EnableWindowsTargeting=true

    - name: Build and publish WebView
      run: dotnet publish HTML2EXE_Webview -c Release -r win-x64 -p:PublishSingleFile=true --self-contained false -o ./webview_publish -p:EnableWindowsTargeting=true

    - name: Create webview.zip
      run: |
        cd webview_publish
        zip ../webview.zip Webview.exe WebView2Loader.dll
        cd ..

    - name: Upload main app artifact
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: ./publish/*

    - name: Upload webview.zip artifact
      uses: actions/upload-artifact@v4
      with:
        name: webview-zip
        path: ./webview.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Create latest.json
      run: |
        echo "{
          \"version\": ${{ github.run_number }},
          \"pub_date\": \"${{ env.RELEASE_DATE }}\",
          \"update\": true,
          \"url\": \"https://github.com/jgc777/HTML2EXE-2.0/releases/download/${{ env.TAG_NAME }}/HTML2EXE.exe\"
          \"url_big\": \"https://github.com/jgc777/HTML2EXE-2.0/releases/download/${{ env.TAG_NAME }}/HTML2EXE-big.exe\"
        }" > latest.json

    - name: Download main app artifact
      uses: actions/download-artifact@v4
      with:
        name: published-app
        path: ./app

    - name: Download webview.zip artifact
      uses: actions/download-artifact@v4
      with:
        name: webview-zip
        path: ./

    - name: Download HTML2EXE-big.exe artifact
      uses: actions/download-artifact@v4
      with:
        name: HTML2EXE-big
        path: ./

    - name: Download webview-big.exe artifact
      uses: actions/download-artifact@v4
      with:
        name: webview-big
        path: ./

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        name: "Build ${{ github.run_number }}"
        tag: ${{ github.run_number }}
        body:  |
            - HTML2EXE.exe and webview.zip (both require [.NET 8.0](https://builds.dotnet.microsoft.com/dotnet/Sdk/8.0.408/dotnet-sdk-8.0.408-win-x64.exe)). To use it, just download [HTML2EXE.exe](https://github.com/jgc777/HTML2EXE-2.0/releases/latest/download/HTML2EXE.exe) and run it.
            - latest.json (for auto-update)
            - HTML2EXE-big.exe and webview-big.exe (both are self-contained and do not require .NET 8.0). To use it, just download [HTML2EXE-big.exe](https://github.com/jgc777/HTML2EXE-2.0/releases/latest/download/HTML2EXE-big.exe) and run it.
            > ${{ github.event.head_commit.message }}
            > Diff: ${{ github.event.before }}...${{ github.sha }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: |
          ./app/*
          ./webview.zip
          ./latest.json
          ./HTML2EXE-big.exe
          ./webview-big.exe
        overwrite: true
        overwrite_assets: true
        draft: false
        prerelease: false