name: Publish for .NET 8.0

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - '*.yml'
      - '.gitignore'
      - 'LICENSE'
      - 'latest.json'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up .NET 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Set build number
      run: |
        FILE="src/HTML2EXE 2.0/Program.cs"
        sed -i 's/private static readonly string CurrentVersion = .*;/private static readonly string CurrentVersion = '${{ github.run_number }}';/' $FILE

    - name: Restore dependencies
      run: dotnet restore -p:EnableWindowsTargeting=true

    - name: Build and publish main app
      run: dotnet publish "HTML2EXE 2.0" -c Release -r win-x64 -p:PublishSingleFile=true --self-contained false -o ./publish -p:PublishReadyToRun=true -p:EnableWindowsTargeting=true

    - name: Build and publish WebView
      run: dotnet publish HTML2EXE_Webview -c Release -r win-x64 -p:PublishSingleFile=true --self-contained false -o ./webview_publish -p:EnableWindowsTargeting=true

    - name: Create webview.zip
      run: |
        cd webview_publish
        zip ../webview.zip Webview.exe WebView2Loader.dll
        cd ..

    - name: Upload main app artifact
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: ./publish/*

    - name: Upload webview.zip artifact
      uses: actions/upload-artifact@v4
      with:
        name: webview-zip
        path: ./webview.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download main app artifact
      uses: actions/download-artifact@v4
      with:
        name: published-app
        path: ./app

    - name: Download webview.zip artifact
      uses: actions/download-artifact@v4
      with:
        name: webview-zip
        path: ./

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        name: "Build ${{ github.run_number }}"
        tag: ${{ github.run_number }}
        body:  |
            Latest Windows binary and webview (both require [.NET 8.0](https://builds.dotnet.microsoft.com/dotnet/Sdk/8.0.408/dotnet-sdk-8.0.408-win-x64.exe)).
            To use it, just download [HTML2EXE.exe](https://github.com/jgc777/HTML2EXE-2.0/releases/latest/download/HTML2EXE.exe) and run it.
            > ${{ github.event.head_commit.message }}
            > Diff: ${{ github.event.before }}...${{ github.sha }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: |
          ./app/*
          ./webview.zip

  create-latest-json:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set environment variables
        run: |
          echo "TAG_NAME=${{ github.run_number }}" >> $GITHUB_ENV
          echo "RELEASE_DATE=$(date +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
      
      - name: Create latest.json
        run: |
          echo "{
            \"version\": ${{ github.run_number }},
            \"pub_date\": \"${{ env.RELEASE_DATE }}\",
            \"url\": \"https://github.com/jgc777/HTML2EXE-2.0/releases/download/${{ env.TAG_NAME }}/HTML2EXE.exe\"
          }" > latest.json

      - name: Update latest.json
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: "Update latest.json for build ${{ env.TAG_NAME }}"
          add: "latest.json"