name: Publish for .NET 8.0

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - '*.yml'
      - 'LICENSE'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up .NET 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore -p:EnableWindowsTargeting=true

    - name: Build and publish main app
      run: dotnet publish "HTML2EXE 2.0" -c Release -r win-x64 -p:PublishSingleFile=true --self-contained false -o ./publish -p:PublishReadyToRun=true -p:EnableWindowsTargeting=true

    - name: Build and publish WebView
      run: |
        dotnet publish HTML2EXE_Webview -c Release -r win-x64 -p:PublishSingleFile=true --self-contained false -o ./webview_publish -p:EnableWindowsTargeting=true

    - name: Create webview.zip
      run: |
        cd webview_publish
        rmdir /f /s runtimes
        zip -r ../webview.zip ./*
        cd ..

    - name: Upload main app artifact
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: ./publish/*

    - name: Upload webview.zip artifact
      uses: actions/upload-artifact@v4
      with:
        name: webview-zip
        path: ./webview.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download main app artifact
      uses: actions/download-artifact@v4
      with:
        name: published-app
        path: ./app

    - name: Download webview.zip artifact
      uses: actions/download-artifact@v4
      with:
        name: webview-zip
        path: ./

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        name: "Build ${{ github.run_number }}"
        tag: ${{ github.run_number }}
        body: "Latest windows binary and webview (requires .NET 8.0). To use it, just download HTML2EXE.exe and run it."
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: |
          ./app/*
          ./webview.zip